services:
  api:
    env_file:
      - .env.dev

  db:
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}/tcp"
    env_file:
      - .env.dev

  redis:
    ports:
      - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}/tcp"

  jaeger:
    ports:
      - "127.0.0.1:${JAEGER_UI_PORT}:${JAEGER_UI_PORT}/tcp"
